namespace Aldaman.Services.Interfaces;

/// <summary>
/// Service interface for sanitizing HTML output generated by rich text editors before storing in persistence.
/// </summary>
public interface IHtmlSanitizerService
{
    /// <summary>
    /// Sanitizes raw HTML string by stripping unauthorized elements, scripts, and unsafe attributes.
    /// </summary>
    /// <param name="rawHtml">The unsanitized HTML input.</param>
    /// <returns>A sanitized HTML string safe for rendering and storage.</returns>
    string Sanitize(string? rawHtml);
}
